name: CI Pipeline
on: [push]

jobs:
  test:
    container: mcr.microsoft.com/dotnet/sdk:7.0
    name: build and test
    runs-on: ubuntu-latest
    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "y"
          MSSQL_PID: "Express"
          MSSQL_SA_PASSWORD: ${{ secrets.DBPASSWORD }}
    env:
      ConnectionStrings__db: ${{ secrets.CONNSTR }}
    steps:
      - uses: actions/checkout@v3
      - run: dotnet build
      - run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-reportgenerator-globaltool
      - run: dotnet test --no-build --collect:"XPlat Code Coverage"
      - run: |
          dotnet reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:"${{ github.workspace }}/CoverageReport" -reporttypes:Html
      - name: Coverage
        uses: actions/upload-artifact@v3
        with:
          name: Coverage
          retention-days: 1
          path: "${{ github.workspace}}/CoverageReport"
